### PR TITLE
Implement location search for locality coordinate selection map

### PR DESCRIPTION
**Pull request by realtalin**
#378

### CODE REVIEW

**Comment by realtalin** [comment]
#502 and #503 done

**Comment by realtalin** [comment]
This is complete enough to merge, as soon as we get an environment variable for the GeoNames username set up for staging. Test, documentation and notifying the user when the search comes back empty still need to be done, but not critical for merge.

**Comment by realtalin** [comment]
Ready to merge!

**Review by iritmaximus — APPROVED** [review]
LGTM

**Pull request merged**
