### PR TITLE
increase the font of name of headers in detail views

### PR DESCRIPTION
**Pull request by EeroAnt**
Increased the font-size. I'm not entirely happy how it positions it differently depending on where in the list is it and also too long names just fade out, but neither of these might be real problems.

### CODE REVIEW

**Comment by EeroAnt** [comment]
relates to #159

**Comment by realtalin** [comment]
Looks better than before, but I'll work on this branch before merge

**Comment by iritmaximus** [comment]
@realtalin is this ready?

**Comment by realtalin** [comment]
> @realtalin is this ready?

Yep, sorry for leaving it in limbo. Still doesn't look great imo, but I need to read up on react if I want to make more major changes (or someone who knows React)

**Review by iritmaximus — APPROVED** [review]

**Pull request merged**
