### PR TITLE
Time Unit api-tests for invalid bounds

### PR DESCRIPTION
**Pull request by Deeroil**
Some api tests for invalid bounds (for create and update).

To-do in this or a later PR:
- should I test the update logs?
- frontend tests?

### CODE REVIEW

**Comment by iritmaximus** [comment]
At least e2e tests could be written in a separate pr.

**Comment by Deeroil** [comment]
Ah oops, testing the update logs would be useless, as in case of invalid bounds nothing is changed :D

**Review by juhanikat — CHANGES_REQUESTED** [review]
Some issues:
1. This part edits "upper_bnd" to null, it should be "up_bnd"
image
2. There's no tests for bounds that have conflicting ages (upper bound is older than lower bound). These don't have to be a part of this pr of course but they're important to test.

**Comment by Deeroil** [comment]
1. Yeah I just noticed the typos as well :D

2. I  think there are? Or at least tries to be, the "Invalid Lower bound causes 500 server error" and upper bound as well, the naming is a bit confusing

**Comment by juhanikat** [comment]
2. You should change the titles to something like "lower bound with invalid age causes 500 server error" imo

**Comment by Deeroil** [comment]
Yeah I didn't know the low_bnd and up_bnd are ids and not age values so I have to redo some stuff anyways :D thanks for help

**Review by iritmaximus — APPROVED** [review]
LGTM

**Pull request merged**
