### PR TITLE
more validators for references, date selection for references

### PR DESCRIPTION
**Pull request by kaarleol**
And some changes to handle dates in different components

### CODE REVIEW

**Comment by kaarleol** [comment]
Still requires some finetuning & rewriting tests but merging should be fine

**Review by realtalin — COMMENTED** [review]
Didn't look over everything, but tests could be skipped using "it.skip", rather than commented out. They will then show as skipped in the logs after running tests, making sure we don't forget about any skipped tests that need to be changed.

**Review by realtalin — APPROVED** [review]
lgtm, a few comments though (none of which are need to be in the scope of this PR)

The error messages shown to the user should probably not use the db column names, but user-visible names. For example, I have no idea what "secondary_field" refers to most of the time. I don't know how much work that would involve.

The typing of handleSetEditData should also be changed, as it's silly to have to type all functions passed as that parameter to handle all types any function passed as that parameter can function. I wrote an issue about this: #531 

Also, I'm not sure adding the field regexCheck to validators is necessary. Is there some reason asString doesn't work for this use case?

**Comment by realtalin** [comment]
Forgot to mention that the validator README should be updated to explain the new fields!

**Pull request merged**
